### ISSUE TITLE
你好，DZMeBookRead这个项目里面 正文最后一行最后一个字跟右边界有多余的空白间隔，请教一下这个问题的解决方法？

### ISSUE THREAD

**Issue by YumikoAzu** [coyingcat/TxtReader#1]
如下图最后一行最后一个字离右边缺了一块。癫字后面:
![0189E511-2159-4792-881B-3AE81B8382FA](https://user-images.githubusercontent.com/13196251/105618285-7df36680-5e20-11eb-82ae-71e6112eb9b8.png)

**Comment by BoxDengJZ** [comment]
This is the way line breaking 

<hr>

DZMReadConfigure.swift

line 186

I added `paragraphStyle.lineBreakMode = .byCharWrapping`
